### ISSUE TITLE
Running cabal test in a sandbox hits version issue

### ISSUE THREAD

**Issue by tonymorris** [data61/fp-course#109]
Running `cabal test` in a sandbox (per the `README`) runs into an issue with a conflicting version of the `Cabal` package in the sandbox versus the global space.

This issue is documented [here](https://github.com/haskell/cabal/issues/1953).

**Comment by gwils** [comment]
You can now use the built-in test runner with no need for cabal.
If you really want to use cabal for some reason, `cabal new-test` should work.
