### ISSUE TITLE
Add Parser.applyParser

### ISSUE THREAD

**Issue by thomie** [data61/fp-course#114]
I noticed that for all Parser exercises except `satisfy`, the full power of `bindParser` is not necessary, and an `applyParser` function can be used instead.

But maybe it was a didactic choice to use `bindParser` instead of `applyParser`?

If not, I could prepare a pull request to add an `applyParser` exercise, change the /Tips/ to mention it, and update the solutions.

**Comment by gwils** [comment]
Today this is solved by the Applicative instance. While running the course, Tony will often swap back and forth between the applicative and monadic styles.
