### ISSUE TITLE
Consider using TypedHoles instead of error

### ISSUE THREAD

**Issue by tonymorris** [data61/fp-course#122]
Also, consider a descriptive data type for exercises instead of just "todo" thereby better indicating where the hole is.

Articles:

https://wiki.haskell.org/GHC/Typed_holes
http://www.shimweasel.com/2015/02/17/typed-holes-for-beginners/

**Comment by mwotton** [comment]
well, _I_ like this, obviously :)

**Comment by tonymorris** [comment]
For example, https://gist.github.com/tonymorris/61d5aa672614e86d59fd

**Comment by gwils** [comment]
Typed holes have been integrated into the course, but not in this specific way.
