### ISSUE TITLE
Basic tictactoe project has no starter contents

### ISSUE THREAD

**Issue by juliangamble** [data61/fp-course#162]
Would be great before you tackle the network TicTacToe to build confidence with a Basic TicTacToe course. 
At the moment the directory is empty: https://github.com/NICTA/course/tree/master/projects/TicTacToe

I realise you're thinking of a rewrite in meantime: https://github.com/NICTA/course/issues/106 (but we don't all think it is insane).

**Comment by gwils** [comment]
There is a README describing what to do. There is no skeleton project because the problem description does not prescribe Haskell. This is also an opportunity for the student to learn about Haskell tooling and use their preferred tool.
