### ISSUE TITLE
Remove semigroupoid way of thinking

### ISSUE THREAD

**Issue by tonymorris** [data61/fp-course#164]
For the purposes of learning and the goals of the course, I am of the opinion that it is beneficial to remove the splitting of:
- `Applicative` to `Apply`
- `Monad` to `Bind`
- `Comonad` to `Extend`

Propose to merge them all together. This also has the benefit of being closer to Haskell-proper after the [AMP changes](https://wiki.haskell.org/Functor-Applicative-Monad_Proposal).

**Comment by tonymorris** [comment]
Perhaps leave `Extend` and `Comonad` separate, since there are exercises that involve the `Extend` instances for `List` and `Optional` (for which there is no `Comonad` instance).

**Comment by yuvallanger** [comment]
I believe that their removal is a mistake. As I was completing these exercises a few days ago, I've found the separation of Applicative into Apply and Bind very illuminating. I urge you to reconsider.

BTW, many thanks for the course material. It is fantastic.

**Comment by dpkatz** [comment]
Could you please update the recommended module progression in README.markdown to get rid of references the `Course.Apply` and `Course.Bind` modules now that they've gone away?  It is *very* confusing to be trying to work through the recommended progression and then find that the modules in question simply don't exist at all.  I spent quite a while wondering if I was at the wrong repository or something before I finally thought to start looking at the issues list...

And I too wish to take the opportunity to thank you for the wonderful course.
