### ISSUE TITLE
cabal repl fails

### ISSUE THREAD

**Issue by apoorvingle** [data61/fp-course#177]
cabal works fine while building and installing

``` bash
$ cabal sandbox init
$ cabal build
$ cabal install
```

but, repl command fails

``` bash
$ cabal repl
Preprocessing library course-0.1.4...
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help

<interactive>:1:6-66: error: Not in scope: ‘>>’

<interactive>:1:70-131: error: Not in scope: ‘>>’

<interactive>:1:135-196: error: Not in scope: ‘return’
```

Is it because it is not supported?

**Comment by tonymorris** [comment]
This is due to having `RebindableSyntax` in the .cabal file.

**Comment by gwils** [comment]
Typically one runs `ghci` to use the course, although in the past it has been necessary to use cabal to run the executable tests.
You should no longer need cabal at all, even to run the tests. See the README section on the built-in test runner.

If you still want to use cabal for some reason, cabal new-repl should work.
