### ISSUE TITLE
Use GADT syntax for data definitions to emphasise the role and the types of constructors

### ISSUE THREAD

**Issue by axman6** [data61/fp-course#189]
As soon as we hit `Id` (now `ExactlyOne`), students often get confused by the use of the same constructor name as the type - The use of GADT syntax, followed later by the standard syntax as a shorthand may make this less problematic.

Opening this as a point for discussion more than anything.

**Comment by gwils** [comment]
I agree this can be confusing, but having a constructor with the same name as its type is a common pattern in Haskell code, so this I would prefer to keep this in as a teaching moment.
When running the course in person, Tony will mention this when he talks about constructors.
