### ISSUE TITLE
One of List's tests relies on another exercise

### ISSUE THREAD

**Issue by horttanainen** [data61/fp-course#213]
```
lengthTest :: TestTree
lengthTest =
   testGroup "length" [
     testCase "length 1..3" $ length (1 :. 2 :. 3 :. Nil) @?= 3
   , testProperty "summing a list of 1s is equal to its length" $
       forAllShrink genIntegerList shrinkList (\x -> sum (map (const 1) x) == length x)
   ]
```
where case: "summing a list of 1s is equal to its length" relies on map, but map is supposed to be implemented after length:
```
-- | Return the length of the list.
--
-- >>> length (1 :. 2 :. 3 :. Nil)
-- 3
--
-- prop> sum (map (const 1) x) == length x
length ::
  List a
  -> Int
length =
  foldRight (\_ acc -> acc + 1) 0

-- | Map the given function on each element of the list.
--
-- >>> map (+10) (1 :. 2 :. 3 :. Nil)
-- [11,12,13]
--
-- prop> headOr x (map (+1) infinity) == 1
--
-- prop> map id x == x
map ::
  (a -> b)
  -> List a
  -> List b
map
  f = foldRight (\el acc -> (f el) :. acc) Nil
```

**Comment by tonymorris** [comment]
Yeah, not sure what to do about things like this.

How about `foldLeft (const . (+1)) 0 (1 :. 2 :. 3 :. Nil)`

But then it is harder to read for when you are writing `map`.

Then how about: `let length' = foldLeft (const . (+1)) 0 in length' (1 :. 2 :. 3 :. Nil)` but now this blatantly spoils the `length` exercise.

**Comment by ajmccluskey** [comment]
We could use `Prelude`'s implementation of `map`/`fmap` in the test and switch between list implementations with `listh` and `hlist`. Again, that'd be a bit messy.

**Comment by tonymorris** [comment]
Or prelude `length`.

**Comment by ajmccluskey** [comment]
That's probably nicest.

**Comment by horttanainen** [comment]
Same problem with flatten and flatMap. case: "sum of lengths == sum of flattened" relies on flatMap being done

**Comment by horttanainen** [comment]
In **Applicative** tests for **<$$>** rely on <*> being implemented for ExactlyOne and List

**Comment by horttanainen** [comment]
In **State** test for **=<<** relies on **put** being done.

**Comment by horttanainen** [comment]
In **StateT** test for **<$>** relies on **Applicative instance** being done for StateT

**Comment by horttanainen** [comment]
In **StateT** test for **=<<** relies on **putT** being done

**Comment by ajmccluskey** [comment]
Thanks a lot for reporting these @horttanainen. I'm just starting to look through them now. I'll hopefully have a branch of fixes ready to merge soon.

**Comment by horttanainen** [comment]
In Parser.hs list1's tip recommends using list and list's tip recommends using list1.
```
-- | Return a parser that continues producing a list of values from the given parser.
--
-- /Tip:/ Use @list1@, @valueParser@ and @(|||)@.
--
-- >>> parse (list character) ""
-- Result >< ""
--
-- >>> parse (list digit) "123abc"
-- Result >abc< "123"
--
-- >>> parse (list digit) "abc"
-- Result >abc< ""
--
-- >>> parse (list character) "abc"
-- Result >< "abc"
--
-- >>> parse (list (character *> valueParser 'v')) "abc"
-- Result >< "vvv"
--
-- >>> parse (list (character *> valueParser 'v')) ""
-- Result >< ""
list ::
  Parser a
  -> Parser (List a)
list =
  error "todo: Course.Parser#list"

-- | Return a parser that produces at least one value from the given parser then
-- continues producing a list of values from the given parser (to ultimately produce a non-empty list).
--
-- /Tip:/ Use @bindParser@, @list@ and @valueParser@.
--
-- >>> parse (list1 (character)) "abc"
-- Result >< "abc"
--
-- >>> parse (list1 (character *> valueParser 'v')) "abc"
-- Result >< "vvv"
--
-- >>> isErrorResult (parse (list1 (character *> valueParser 'v')) "")
-- True
list1 ::
  Parser a
  -> Parser (List a)
list1 =
  error "todo: Course.Parser#list1"
```

**Comment by ajmccluskey** [comment]
Here's a summary of issues to be checked off.

- [x] `List.length` (see #216)
- [x] `List.flatten` (see #216)
- [x] `Applicative.(<$$>)` (see #217)
- [ ] `State.(=<<)`
- [ ] `StateT.(<$>)`
- [ ] `StateT.(=<<)`
