### ISSUE TITLE
Error compiling source code: Module ‘Distribution.Package’ does not export ‘PackageName(PackageName)’

### ISSUE THREAD

**Issue by hpcsc** [data61/fp-course#214]
Hi, 

Just clone this repository to my local machine and following the instructions to run the tests and have this error:

<img width="1070" alt="screen shot 2017-08-17 at 10 30 21 am" src="https://user-images.githubusercontent.com/5293047/29393619-6522085e-8337-11e7-87b5-eb92bbfaba9c.png">

Any idea what have I done wrong?
My cabal version: 
```
cabal-install version 2.0.0.0
compiled using version 2.0.0.2 of the Cabal library
```

Thanks

**Comment by dalaing** [comment]
It looks like it's related to [this](https://github.com/ekmett/lens/issues/709).  I'm trying some things out that might help...

**Comment by dalaing** [comment]
I've just pushed a change for that - could you grab the latest version from master and see if that helps at all?

**Comment by hpcsc** [comment]
awesome, it's working now. Thanks for the quick response and fix
