### ISSUE TITLE
Need detail example in getting started instruction.

### ISSUE THREAD

**Issue by wizzup** [data61/fp-course#220]
I am on NixOS. I try to follow instructions from [Getting Started](https://github.com/data61/fp-course#getting-started)

* [x] Install the Glasgow Haskell Compiler (GHC) version 7.10 or higher.
* [x] Change to the directory containing this document.
~~~
    [wizzup@ fp-course] (master) 
    $ git rev-parse HEAD
    c6e55089b0fbd0356a82d4446b4614edeb481e31
    [wizzup@ fp-course] (master) 
    $ nix-shell

    [nix-shell:/data/learn/fp-course]$ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 8.0.2
~~~
* [x] Execute the command ghci, which will compile and load all the source code. You may need to set permissions on the root directory and the ghci configuration file, chmod 600 .ghci ./.
~~~
    [nix-shell:/data/learn/fp-course]$ ghci
    GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
    [ 1 of 26] Compiling Course.Core      ( src/Course/Core.hs, interpreted )
    <...>
    [26 of 26] Compiling Course           ( src/Course.hs, interpreted )
    Ok, modules loaded: Course, Course.Anagrams, Course.Applicative, Course.Cheque, Course.Comonad, Course.Compose, Course.Core, Course.ExactlyOne, Course.Extend, Course.FastAnagrams, Course.FileIO, Course.Functor, Course.Interactive, Course.JsonParser, Course.JsonValue, Course.List, Course.ListZipper, Course.Monad, Course.MoreParser, Course.Optional, Course.Parser, Course.Person, Course.State, Course.StateT, Course.Traversable, Course.Validation.
    Loaded GHCi configuration from /data/learn/fp-course/.ghci
    Loaded GHCi configuration from /data/works/dotfiles/ghci
    >> 
~~~

From this point on, I have no idea what to do next with remaining steps. A trivial concrete example would be very helpful.
I [found](https://github.com/data61/fp-course#progression) that I should start with `Course.ExactlyOne` but have no idea what it really mean.

---

* Inspect the introductory modules to get a feel for Haskell's syntax, then move on to the exercises starting with Course.Optional. The Progression section of this document lists the recommended order in which to attempt the exercises.

* Edit a source file to a proposed solution to an exercise. At the ghci prompt, issue the command :reload. This will compile your solution and reload it in the GHC interpreter. You may use :r for short.

**Comment by wizzup** [comment]
I just found [this](https://www.youtube.com/watch?v=NzIZzvbplSM} video that help me.

**Comment by puffnfresh** [comment]
Awesome! @wizzup :heart:
