### ISSUE TITLE
produce in List.hs already done

### ISSUE THREAD

**Issue by polynomial** [data61/fp-course#226]
https://github.com/data61/fp-course/blob/master/src/Course/List.hs#L319

I'm not sure, but is this already supposed to be completed in this repo?

**Comment by tonymorris** [comment]
Yeah, we decided it's not a very useful exercise, but is needed later for others.

**Comment by polynomial** [comment]
Thanks for the explanation, and also thank you so much for this repo. I appreciate the exercises! 🙃
