### ISSUE TITLE
OptionalT Monad is not compatible with its Applicative instance

### ISSUE THREAD

**Issue by Lysxia** [data61/fp-course#269]
https://github.com/data61/fp-course/blob/master/src/Course/StateT.hs#L219-L235

Good `Monad` and `Applicative` instances should satisfy `(<*>) = (<**>)` ([see the doc for `Monad` in *base*](https://hackage.haskell.org/package/base-4.11.0.0/docs/Control-Monad.html#t:Monad) for reference), but compare:

    OptionalT (Full (+1) :. Empty :. Nil) <*>  OptionalT (Full 1 :. Full 2 :. Nil)
    OptionalT (Full (+1) :. Empty :. Nil) <**> OptionalT (Full 1 :. Full 2 :. Nil)

We get, respectively,

    OptionalT (Full 2 :. Full 3 :. Empty :. Empty :. Nil)
    OptionalT (Full 2 :. Full 3 :. Empty :. Nil)

`OptionalT` as a monad transformer should short-circuit evaluation when the first computation returns `Empty` (hence why the second example has only one `Empty`), but there is no way to do so for the `Applicative` instance with only an `Applicative f` constraint.

**Comment by andreabedini** [comment]
This stems from a discussion on Slack, [link](https://functionalprogramming.slack.com/archives/C0433UN0M/p1523407597000282)
