### ISSUE TITLE
flattenAgain exercise spoiled by flatMap exercise in Course.List module

### ISSUE THREAD

**Issue by ZzAntares** [data61/fp-course#271]
Hello, I'm just going through the course and in the `Course.List` module in the exercise for implementing `flattenAgain` we're asked to use `flatMap` to  implement the answer, however just 10ish lines above we have the answer in the properties for the `flatMap` function.

This is the extract of that region of code, see the first line (the answer) and last line (the exercise):

```haskell
-- prop> \x -> flatMap id (x :: List (List Int)) == flatten x
flatMap :: (a -> List b) -> List a -> List b
-- flatMap f = foldRight (\e acc -> f e ++ acc) Nil
-- flatMap f = foldRight (\e -> (f e ++)) Nil
-- flatMap f = foldRight ((++) . f) Nil
flatMap f = flatten . map f

-- | Flatten a list of lists to a list (again).
-- HOWEVER, this time use the /flatMap/ function that you just wrote.
--
-- prop> \x -> let types = x :: List (List Int) in flatten x == flattenAgain x
flattenAgain :: List (List a) -> List a
flattenAgain = flatMap id
```

Perhaps you don't consider this an issue, but I thought it was worth to mention.

**Comment by tonymorris** [comment]
Functional Programming, cheating.

Same Same.
