### ISSUE TITLE
Determine the future of projects/NetworkServer

### ISSUE THREAD

**Issue by gwils** [data61/fp-course#280]
The `projects/NetworkServer` directory contains an optional extra project for a student looking to go further than the intro course material goes, and do something more "real world".

Currently, NetworkServer only works with `cabal new-build`. It does not work with standard `cabal install` unless you are using exactly cabal version 1.24 (which comes with GHC 8.0). Furthermore, even with `new-build` it does not have an install plan for GHC 8.4 (the latest GHC release at the time of writing this issue).

`projects/NetworkServer` should be modernised if we still intend it to be useful. In particular, it should be changed to build with the newest ghc release with `new-build`, and with a greater range of ghcs with old-style cabal. All this could be achieved by an overhaul of the Setup.lhs script.

That being said, I can't help but wonder whether `projects/NetworkServer` is deprecated by our `applied-fp-course`, which also focuses on building a real-world program with a greater scope and more direction than `projects/NetworkServer`. This being the case, it might be worthwhile deleting projects/NetworkServer to avoid the maintenance cost, and instead pointing to the applied course.

**Comment by puffnfresh** [comment]
From what I can see, applied-fp-course should replace the project. My classes haven't done it and we haven't got any plans to.

**Comment by gwils** [comment]
Deleted in favour of applied-fp-course
