### ISSUE TITLE
Documentation: Test pattern option fails

### ISSUE THREAD

**Issue by MIJOTHY** [data61/fp-course#282]
In the docs, the following commands are stated for running tests of a given pattern:  

> `> cabal test tasty --show-detail=direct --test-option=--pattern=Tests/List/`
> 
> Likewise, to run only the tests for the headOr function in the List module, you could use:
> `> cabal test tasty --show-detail=direct --test-option=--pattern=List/headOr`
> 
Both of these fail for me with tasty parse errors on the --pattern option. What do work on the other hand are:  

`> cabal test tasty --show-detail=direct --test-option=--pattern="Tests.List."`
`> cabal test tasty --show-detail=direct --test-option=--pattern="List.headOr"`
(Note the inclusion of quotes and dots rather than slashes). If I'm not missing something and this can be confirmed, I'm happy to do a pull req.

**Comment by gwils** [comment]
Thank you for reporting this!

The problem is caused by the difference in the pattern language used by tasty between tasty <1 and tasty >= 1

I've opened #283 to make the documentation change.
