### ISSUE TITLE
Missing tests for Parser and MoreParser

### ISSUE THREAD

**Issue by etiennebatise** [data61/fp-course#286]
Hi,

The test files for  `Parser.hs`  and `MoreParser.hs` are missing. 

Is this on purpose as an exercice for the student or is this open for PR ? 

 I have the files ready [here](https://github.com/etiennebatise/data61-fp-course/blob/master/test/Course/ParserTest.hs) and [here](https://github.com/etiennebatise/data61-fp-course/blob/master/test/Course/MoreParserTest.hs)

**Comment by ajmccluskey** [comment]
Thanks a lot for the work @etiennebatise. There are already (doc)tests for both of these modules in the course, however they haven't yet been ported to `tasty` (i.e. put in the `test` directory). As a result, the test code is all in comments in those modules and you can use [`doctest`](https://hackage.haskell.org/package/doctest) to run the tests.

I have a PR (#236) to add the `Parser` module's tests already, but it has conflicts that I need to resolve. I'll take a look at your tests when I do that.

As a side note, all of the tests in the `test` directory are a port of the doctests. We're still not 100% how we're going to manage tests in the future, so I'm going to work on resolving that first before committing any more time to producing tests. With that in mind, it might take a little time for me to get back to this -- my apologies!

Thanks again for your efforts!

**Comment by etiennebatise** [comment]
Thank you for your detailed answer. 

FYI, my tests are really just a copy of the doctests because I found it more convenient to run them with `tasty` :smile:.

Also, as I think the `Traversable` module is fundamental brick for the course, is there any plan to test them deeply ? I only ask this because it led me to [this](https://github.com/tonymorris/fp-course/issues/42)  issue involving the `MoreParser` module.

**Comment by puffnfresh** [comment]
@etiennebatise I added most of Traversable to the course. I'd absolutely love to see tests which exercise the problem you encountered.

**Comment by etiennebatise** [comment]
Hi @puffnfresh ,

I detailed the problem in this issue : https://github.com/tonymorris/fp-course/issues/42. 

As you can see, I tracked the problem to the implementation of `traverse`. Really, I have no idea why my solution works.
