### ISSUE TITLE
Rename `f` in `Functor f`

### ISSUE THREAD

**Issue by LightAndLight** [data61/fp-course#287]
@tonymorris

**Comment by endgame** [comment]
IRL Tony mentioned using `k`. I suggest using `j` so when you go to fix `newtype Compose f g a = Compose (f (g a))` you get the natural `newtype Compose j k a = Compose (j (k a))` instead of reaching for `l` which looks like `1`, or pulling letters in reverse order, or whatever.

**Comment by gwils** [comment]
closed as duplicate
