### ISSUE TITLE
Dumb but obvious question

### ISSUE THREAD

**Issue by gsklee** [data61/fp-course#294]
I'm going to ask this dumb but obvious question for all Haskell newbies like me out there:

What do I do next after typing in `ghci` and staring at this interactive prompt?

**Comment by tonymorris** [comment]
These exercises.

https://github.com/data61/fp-course/blob/master/README.markdown#progression

**Comment by gsklee** [comment]
@tonymorris Exactly. Now how do I do that in the prompt? Or does "inspect the introduction modules" simply means opening the source code in some IDE?

**Comment by wizzup** [comment]
duplicate #220 ?

**Comment by gwils** [comment]
This question was not dumb :)
The README has been updated, so it should now be clear. Thanks for bringing this to our attention.
