### ISSUE TITLE
Are there any up to date solution somewhere?

### ISSUE THREAD

**Issue by wizzup** [data61/fp-course#328]
The reference solution [tonymorris](https://github.com/tonymorris/fp-course) seem to diverge from current master a lot.  

I try searching on github on up-to-date solutions but didn't found any.

For example, I can't find any solution for Applicative [instance](https://github.com/data61/fp-course/blob/f0de6788ea2ce27136b1dd0aa1c4b5669511d39c/src/Course/StateT.hs#L235) of `OptionalT`  that using [onFull](https://github.com/data61/fp-course/blob/f0de6788ea2ce27136b1dd0aa1c4b5669511d39c/src/Course/StateT.hs#L368) as hinted.

----

Some time ago, I create a [PR](https://github.com/tonymorris/fp-course/pull/45) but doesn't seem to get any response (Not a complains by any means, everyone have right to choose what to spends with their time).

Would it be better to have a `solution` branch here that always up-to-date with changes?

**Comment by tonymorris** [comment]
The solutions at https://github.com/tonymorris/fp-course have been updated.
