### ISSUE TITLE
add Alternative typeclass to Applicative.hs

### ISSUE THREAD

**Issue by wizzup** [data61/fp-course#330]
In Parser.hs, there is [(|||)](https://github.com/data61/fp-course/blob/master/src/Course/Parser.hs#L165) which basically is [(<|>)](https://hackage.haskell.org/package/base/docs/Control-Applicative.html#g:2) from `Control.Applicative`.

Having `Alternative` typeclass and some exercises could provide additional knowledge for learner for better understanding `Applicative`-related [concept](https://en.wikibooks.org/wiki/Haskell/Alternative_and_MonadPlus).

**Comment by gwils** [comment]
I suggest instead that Alternative be added in its own module. That way we can more easily avoid it when running the course in person, but the content is still there for someone doing the course on their own.
