### ISSUE TITLE
GitPod is broken

### ISSUE THREAD

**Issue by endgame** [data61/fp-course#375]
The gitpod no longer boots.

I suspect that this is because nixpkgs is unpinned and names a GHC version that no longer exists.

Ping @ghuntley 

*****

I still have reservations about GitPod, and am leaning towards advocating its removal. In #374, I've been cutting out all external dependencies so the course can run with only a text editor and `ghci`, and I removed the leksah files and most of the nix as part of that work, for the following reason:

**The primary purpose of the course repo is to run in a classroom setting for people who have never seen Haskell before, and every file that doesn't end in `.hs` (and many that do!) imposes additional mental overhead on the students.**

GitPod is not frictionless; booting a pod requires clicking through screens that authorise gitpod to access your github account, accepting ToS, etc. The course successfully teaches functional thinking to students who have no github account and no idea what git is; many students in classroom sessions find the "Download ZIP" link and bring that along with them. Reliable internet is also not guaranteed.

**Comment by puffnfresh** [comment]
Could we have the GitPod in a separate repo? Maybe via submodules or something?

**Comment by tonymorris** [comment]
Yeah, separate repo is a good idea imo.
