### ISSUE TITLE
Why no cabal/stack in the nix-pkgs?

### ISSUE THREAD

**Issue by drewboardman** [data61/fp-course#384]
I noticed you changed the build tools to be in `support/`. Is there a reason that these don't include the appropriate build-tools?

Is the assumed work-flow to use system `cabal` with an impure `nix-shell`, and it will just use the project's `ghc` that comes with the nix build?

**Comment by endgame** [comment]
The course does not need a build tool at all. The main workflow is "work on something, `:r` in GHCi, repeat", so the nix files in `support/` only provide `ghc` and `ghcid`.

If your editor needs a build tool, then I think you should either edit the `shell.nix` to provide the tools you want, or use an impure shell.
