### ISSUE TITLE
Document motivation of nicta/course

### ISSUE THREAD

**Issue by tonymorris** [data61/fp-course#96]
Often this material is discussed in the context of beginners using it to kickstart their own learning. However, this material was originally designed (and is still used) in 2007 for person-person tuition. Therefore, it has some shortfalls for people looking to use it for themselves or in a group of peers without appropriate guidance (besides types!).

It is suggested that a document, perhaps included as a section of the README, makes clear that when this material is given to a complete beginner, a few things also occur.
1. Two to fours hours are spent learning Haskell syntax. This starts with an empty file and code is written by introducing syntax. Also, familiarity with tools (e.g. GHC :reload, :type, etc) is gained. This results in a student-created "cheat sheet" that is often referred to for syntax rules later.
2. Often times, a student is not familiar with the idea of trusting and using types to guide to a solution. This is also a difficult mode of thought to document, but it is necessary to communicate this somehow.

Perhaps this syntax issue and problem-solving technique (using types) could be demonstrated in an online video. However, it is a subject that is difficult to get right first time (and second, third) and videos are difficult to incrementally update. It would require a lot of planning and peer input.

**Comment by gwils** [comment]
The README covers this now
